"""Collect the statements of the jeff dialects."""

from . import (
    scf as scf,
    call as call,
    gate as gate,
    wire as wire,
    classical as classical,
)
from .scf import For as For, While as While, Yield as Yield, Switch as Switch
from .call import Call as Call, Return as Return
from .gate import Ppr as Ppr, Gate as Gate
from .wire import (
    Free as Free,
    Alloc as Alloc,
    Reset as Reset,
    Insert as Insert,
    Extract as Extract,
    Measure as Measure,
    RegFree as RegFree,
    RegJoin as RegJoin,
    FreeZero as FreeZero,
    RegAlloc as RegAlloc,
    RegSplit as RegSplit,
    MeasureNd as MeasureNd,
    RegCreate as RegCreate,
    RegLength as RegLength,
    InsertSlice as InsertSlice,
    RegFreeZero as RegFreeZero,
    ExtractSlice as ExtractSlice,
)
from .classical import (
    IntEq as IntEq,
    IntOr as IntOr,
    IntAbs as IntAbs,
    IntAdd as IntAdd,
    IntAnd as IntAnd,
    IntLtS as IntLtS,
    IntLtU as IntLtU,
    IntMul as IntMul,
    IntNot as IntNot,
    IntPow as IntPow,
    IntShl as IntShl,
    IntShr as IntShr,
    IntSub as IntSub,
    IntXor as IntXor,
    FloatEq as FloatEq,
    FloatLt as FloatLt,
    IntDivS as IntDivS,
    IntDivU as IntDivU,
    IntLteS as IntLteS,
    IntLteU as IntLteU,
    IntMaxS as IntMaxS,
    IntMaxU as IntMaxU,
    IntMinS as IntMinS,
    IntMinU as IntMinU,
    IntRemS as IntRemS,
    IntRemU as IntRemU,
    ConstInt as ConstInt,
    FloatAbs as FloatAbs,
    FloatAdd as FloatAdd,
    FloatCos as FloatCos,
    FloatExp as FloatExp,
    FloatLog as FloatLog,
    FloatLte as FloatLte,
    FloatMax as FloatMax,
    FloatMin as FloatMin,
    FloatMul as FloatMul,
    FloatPow as FloatPow,
    FloatSin as FloatSin,
    FloatSub as FloatSub,
    FloatTan as FloatTan,
    IntUnary as IntUnary,
    FloatAcos as FloatAcos,
    FloatAsin as FloatAsin,
    FloatAtan as FloatAtan,
    FloatCeil as FloatCeil,
    FloatCosh as FloatCosh,
    FloatSinh as FloatSinh,
    FloatSqrt as FloatSqrt,
    FloatTanh as FloatTanh,
    IntBinary as IntBinary,
    IntSelect as IntSelect,
    ConstFloat as ConstFloat,
    FloatAcosh as FloatAcosh,
    FloatAsinh as FloatAsinh,
    FloatAtan2 as FloatAtan2,
    FloatAtanh as FloatAtanh,
    FloatFloor as FloatFloor,
    FloatIsInf as FloatIsInf,
    FloatIsNan as FloatIsNan,
    FloatUnary as FloatUnary,
    IntCompare as IntCompare,
    FloatBinary as FloatBinary,
    FloatSelect as FloatSelect,
    IntArrayGet as IntArrayGet,
    IntArrayLen as IntArrayLen,
    IntArraySet as IntArraySet,
    FloatCompare as FloatCompare,
    IntArrayZero as IntArrayZero,
    FloatArrayGet as FloatArrayGet,
    FloatArrayLen as FloatArrayLen,
    FloatArraySet as FloatArraySet,
    IntArrayConst as IntArrayConst,
    FloatArrayZero as FloatArrayZero,
    FloatPredicate as FloatPredicate,
    IntArrayCreate as IntArrayCreate,
    FloatArrayConst as FloatArrayConst,
    FloatArrayCreate as FloatArrayCreate,
)
